# Rad sa MovieLens 100K

In [1]:
import pandas as pd
import numpy as np

In [2]:
header = ['user', 'item', 'rating', 'timestamp']

In [3]:
data = pd.read_csv('ml-100k/u.data', sep = '\\t', names = header)

<ipython-input-3-a89852cab6f7>:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  data = pd.read_csv('ml-100k/u.data', sep = '\\t', names = header)


In [4]:
data.head()

user  item  rating  timestamp
0   196   242       3  881250949
1   186   302       3  891717742
2    22   377       1  878887116
3   244    51       2  880606923
4   166   346       1  886397596

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   user       100000 non-null  int64
 1   item       100000 non-null  int64
 2   rating     100000 non-null  int64
 3   timestamp  100000 non-null  int64
dtypes: int64(4)
memory usage: 3.1 MB


In [6]:
number_of_users = data['user'].unique().shape[0]
number_of_users

943

In [7]:
number_of_items = data['item'].unique().shape[0]
number_of_items

1682

In [8]:
ui_matrix = pd.pivot_table(data, index = 'user', columns = 'item', values = 'rating')

In [9]:
ui_matrix

item  1     2     3     4     5     6     7     8     9     10    ...  1673  \
user                                                              ...         
1      5.0   3.0   4.0   3.0   3.0   5.0   4.0   1.0   5.0   3.0  ...   NaN   
2      4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   2.0  ...   NaN   
3      NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   
4      NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   
5      4.0   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
939    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   5.0   NaN  ...   NaN   
940    NaN   NaN   NaN   2.0   NaN   NaN   4.0   5.0   3.0   NaN  ...   NaN   
941    5.0   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN  ...   NaN   
942    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   
943    NaN   5.0   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN  ...   NaN   

item  1674  1675  1676  1677  1678  1679  1680  1681  1682  
user                                                        
1      NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
2      NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
3      NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
4      NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
5      NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
939    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
940    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
941    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
942    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
943    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[943 rows x 1682 columns]

In [10]:
ui_matrix.describe()

item         1           2          3           4          5          6     \
count  452.000000  131.000000  90.000000  209.000000  86.000000  26.000000   
mean     3.878319    3.206107   3.033333    3.550239   3.302326   3.576923   
std      0.927897    0.966497   1.212760    0.965069   0.946446   1.301478   
min      1.000000    1.000000   1.000000    1.000000   1.000000   1.000000   
25%      3.000000    3.000000   2.000000    3.000000   3.000000   3.000000   
50%      4.000000    3.000000   3.000000    4.000000   3.000000   4.000000   
75%      5.000000    4.000000   4.000000    4.000000   4.000000   5.000000   
max      5.000000    5.000000   5.000000    5.000000   5.000000   5.000000   

item         7           8           9          10    ...  1673  1674  1675  \
count  392.000000  219.000000  299.000000  89.000000  ...   1.0   1.0   1.0   
mean     3.798469    3.995434    3.896321   3.831461  ...   3.0   4.0   3.0   
std      0.982037    1.002281    1.042368   1.013948  ...   NaN   NaN   NaN   
min      1.000000    1.000000    1.000000   1.000000  ...   3.0   4.0   3.0   
25%      3.000000    3.000000    3.000000   3.000000  ...   3.0   4.0   3.0   
50%      4.000000    4.000000    4.000000   4.000000  ...   3.0   4.0   3.0   
75%      5.000000    5.000000    5.000000   5.000000  ...   3.0   4.0   3.0   
max      5.000000    5.000000    5.000000   5.000000  ...   3.0   4.0   3.0   

item   1676  1677  1678  1679  1680  1681  1682  
count   1.0   1.0   1.0   1.0   1.0   1.0   1.0  
mean    2.0   3.0   1.0   3.0   2.0   3.0   3.0  
std     NaN   NaN   NaN   NaN   NaN   NaN   NaN  
min     2.0   3.0   1.0   3.0   2.0   3.0   3.0  
25%     2.0   3.0   1.0   3.0   2.0   3.0   3.0  
50%     2.0   3.0   1.0   3.0   2.0   3.0   3.0  
75%     2.0   3.0   1.0   3.0   2.0   3.0   3.0  
max     2.0   3.0   1.0   3.0   2.0   3.0   3.0  

[8 rows x 1682 columns]

In [11]:
train_data = pd.read_csv('ml-100k/u1.base', sep = '\\t', names = header)

<ipython-input-11-16e948ed58ea>:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  train_data = pd.read_csv('ml-100k/u1.base', sep = '\\t', names = header)


In [12]:
train_data.head()

user  item  rating  timestamp
0     1     1       5  874965758
1     1     2       3  876893171
2     1     3       4  878542960
3     1     4       3  876893119
4     1     5       3  889751712

In [13]:
train_data[train_data['user'] == 1]['item'].unique()

array([  1,   2,   3,   4,   5,   7,   8,   9,  11,  13,  15,  16,  18,
        19,  21,  22,  25,  26,  28,  29,  30,  32,  34,  35,  37,  38,
        40,  41,  42,  43,  45,  46,  48,  50,  52,  55,  57,  58,  59,
        63,  66,  68,  71,  75,  77,  79,  83,  87,  88,  89,  93,  94,
        95,  99, 101, 105, 106, 109, 110, 111, 115, 116, 119, 122, 123,
       124, 126, 127, 131, 133, 135, 136, 137, 138, 139, 141, 142, 144,
       146, 147, 149, 152, 153, 156, 158, 162, 165, 166, 167, 168, 169,
       172, 173, 176, 178, 179, 181, 182, 187, 191, 192, 194, 195, 197,
       198, 199, 203, 204, 205, 207, 211, 216, 217, 220, 223, 231, 234,
       237, 238, 239, 240, 244, 245, 246, 247, 249, 251, 256, 257, 261,
       263, 268, 269, 270, 271], dtype=int64)

In [14]:
test_data = pd.read_csv('ml-100k/u1.test', sep = '\\t', names = header)

<ipython-input-14-3f706b5842e4>:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  test_data = pd.read_csv('ml-100k/u1.test', sep = '\\t', names = header)


In [15]:
test_data.head()

user  item  rating  timestamp
0     1     6       5  887431973
1     1    10       3  875693118
2     1    12       5  878542960
3     1    14       5  874965706
4     1    17       3  875073198

In [16]:
# ui_matrix_train = pd.pivot_table(train_data, index = 'user', columns = 'item', values = 'rating')

In [17]:
ui_matrix_train = np.zeros((number_of_users, number_of_items))
for row in train_data.itertuples():
    ui_matrix_train[row[1]-1, row[2]-2] = row[3]
    
ui_matrix_train.shape

(943, 1682)

In [18]:
ui_matrix_train

array([[3., 4., 3., ..., 0., 0., 5.],
       [0., 0., 0., ..., 0., 0., 4.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 5.],
       [0., 0., 0., ..., 0., 0., 0.],
       [5., 0., 0., ..., 0., 0., 0.]])

In [19]:
train_data['item'].unique().shape[0]

1650

In [20]:
train_data['user'].unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [21]:
number_of_items

1682

In [22]:
test_data['user'].unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [23]:
def calculate_covariance_between_users(ui_matrix, i, j):
    if (i != j):
        ratings_i = ui_matrix[i,:]
        ratings_j = ui_matrix[j,:]
    
        common_items = (ratings_i != 0) & (ratings_j != 0)
    
        part1 = np.sum(ratings_i[common_items]*ratings_j[common_items])*(1/number_of_items)
        part2 = np.sum(ratings_i)*np.sum(ratings_j)*(1/(number_of_items**2))
    
        return part1 - part2
    else:
        return float('inf')

In [24]:
calculate_covariance_between_users(ui_matrix_train, 1, 2)

0.008566609310867957

In [25]:
calculate_covariance_between_users(ui_matrix_train, 2, 1)

0.008566609310867957

In [26]:
calculate_covariance_between_users(ui_matrix_train, 100, 99)

-0.004150401325640022

In [27]:
covariance_matrix = np.zeros((number_of_users, number_of_users))
for i in range(number_of_users):
    for j in range(i, number_of_users):
        covariance_matrix[i, j] = calculate_covariance_between_users(ui_matrix_train, i, j)
        covariance_matrix[j, i] = covariance_matrix[i, j]

In [28]:
covariance_matrix

array([[        inf,  0.03810155,  0.00961923, ...,  0.06700484,
         0.07872932,  0.21979136],
       [ 0.03810155,         inf,  0.00856661, ...,  0.03326825,
         0.05383221,  0.03996361],
       [ 0.00961923,  0.00856661,         inf, ...,  0.01400433,
         0.02209871, -0.00750055],
       ...,
       [ 0.06700484,  0.03326825,  0.01400433, ...,         inf,
         0.03458279,  0.03369842],
       [ 0.07872932,  0.05383221,  0.02209871, ...,  0.03458279,
                inf,  0.12853484],
       [ 0.21979136,  0.03996361, -0.00750055, ...,  0.03369842,
         0.12853484,         inf]])

In [29]:
covariance_matrix[10, 20]

0.008439714908218932

In [30]:
covariance_matrix[20, 10]

0.008439714908218932

In [31]:
covariance_matrix[942, 0]

0.21979135591087556

In [32]:
covariance_matrix[0, 942]

0.21979135591087556

In [33]:
def GetKSimilarUser(user_i, K):
    user_values = covariance_matrix[user_i,:]
    values = user_values.argsort()[-K-1:]
    
    return values[0:K]

In [34]:
print(GetKSimilarUser(0, 10))
for i in GetKSimilarUser(0,10):
    print(covariance_matrix[0, i])

[415 888 746 605 456 513 473 822 863 591]
0.4247661113475408
0.43463771824776853
0.44647318392548363
0.44853106473947413
0.4494610345817291
0.45235804439819527
0.47118436660959356
0.4804091301759837
0.49576618062693606
0.5263399554066912


In [35]:
def GetKDSimilarUser(user_i, K):
    user_values = covariance_matrix[user_i,:]
    
    return user_values.argsort()[:K]

In [36]:
def CFCM(UI, user_u, alpha, K, N):
    Nus = GetKSimilarUser(user_u, K)
    Nud = GetKDSimilarUser(user_u, K)
    
    # prosecna ocena koju je dao user, izracunata samo nad itemima koji nisu 0
    ru_average = UI[user_u-1, UI[user_u-1, :] != 0].mean()
    # niz predvidjenih ocena za sve iteme
    all_predicted_ratings = np.zeros(number_of_items)
    # drugo, krace ime za matricu kovarijansi
    COV = covariance_matrix
    
    
    for item_i in range(number_of_items):
        
        # za racunanje dela iznad razlomacke crte u prvom delu gde se posmatraju slicni
        similar = np.zeros(K)
        # za racunanje dela ispod razlomacke crte u prvom delu gde se posmatraju slicni
        divide_s = np.zeros(K)
        # za racunanje dela iznad razlomacke crte u drugom delu gde se posmatraju razliciti
        disimilar = np.zeros(K)
        # za racunanje dela ispod razlomacke crte u drugom delu gde se posmatraju razliciti
        divide_ds = np.zeros(K)
    
        for i in range(K):
            similar[i] = COV[user_u-1, Nus[i]]*(UI[Nus[i],item_i-1] - UI[Nus[i], :].mean())
            divide_s[i] = np.abs(COV[user_u-1, Nus[i]])
            disimilar[i] = np.abs(COV[user_u-1, Nud[i]])*(UI[Nud[i],item_i-1] - UI[Nud[i], :].mean())
            divide_ds[i] = np.abs(COV[user_u-1, Nud[i]])
        
        # formula iz algoritma
        rui = ru_average + alpha * (np.sum(similar)/np.sum(divide_s)) + (1-alpha) * (np.sum(disimilar)/np.sum(divide_ds))
        # za svaki element stavljamo u niz
        all_predicted_ratings[item_i] = rui
        # print(rui) --> kad se isprintuju sve predvidjene ocene vidi se da su neke vece od 5
        
        if (item_i == 173):
            print(all_predicted_ratings[item_i])
        
    # uzimamo prvih N najboljih predloga za usera u     
    Result = np.flipud(all_predicted_ratings.argsort())[:N]
    return Result

In [37]:
CFCM(ui_matrix_train, 200, 0.8, 10, 5)

6.990385661659858


array([ 97, 126, 202, 179,  78], dtype=int64)

In [38]:
CFCM(ui_matrix_train, 1, 0.8, 10, 5)

5.324089064100154


array([ 49, 301, 257, 312,   6], dtype=int64)

In [39]:
test_data[test_data['item'] == 174]

user  item  rating  timestamp
80        1   174       5  875073198
420       7   174       5  891350757
1085     14   174       5  890881294
1192     16   174       5  877719504
1636     25   174       5  885853415
...     ...   ...     ...        ...
18829   394   174       5  881057914
18850   395   174       5  883763561
19307   407   174       5  875042675
19447   416   174       5  893213917
19789   436   174       3  887769335

[76 rows x 4 columns]